export const HAN_VIET_DATA: Record<string, string> = {
  "学": "Học",
  "习": "Tập",
  "老": "Lão",
  "师": "Sư",
  "生": "Sinh",
  "谢": "Tạ",
  "不": "Bất",
  "客": "Khách",
  "气": "Khí",
  "你": "Nhĩ",
  "好": "Hảo",
  "您": "Nâm",
  "早": "Tảo",
  "对": "Đối",
  "起": "Khởi",
  "没": "Một",
  "关": "Quan",
  "系": "Hệ",
  "再": "Tái",
  "见": "Kiến",
  "多": "Đa",
  "少": "Thiểu",
  "这": "Giá",
  "那": "Na",
  "谁": "Thùy",
  "哪": "Nào",
  "什么": "Thập ma",
  "在": "Tại",
  "哪儿": "Nào nhân",
  "去": "Khứ",
  "回": "Hồi",
  "来": "Lai",
  "吃": "Ngật",
  "饭": "Phạn",
  "喝": "Hát",
  "水": "Thủy",
  "茶": "Trà",
  "咖啡": "Gia phi",
  "苹果": "Bình quả",
  "面包": "Miện bao",
  "中国": "Trung Quốc",
  "越南": "Việt Nam",
  "汉": "Hán",
  "语": "Ngữ",
  "字": "Tự",
  "听": "Thính",
  "说": "Thuyết",
  "读": "Độc",
  "写": "Tả",
  "看": "Khán",
  "做": "Tác",
  "买": "Mãi",
  "卖": "Mại",
  "是": "Thị",
  "有": "Hữu",
  "要": "Yêu",
  "给": "Cấp",
  "找": "Trảo",
  "钱": "Tiền",
  "岁": "Tuế",
  "点": "Điểm",
  "分": "Phân",
  "秒": "Miểu",
  "现在": "Hiện tại",
  "今天": "Kim thiên",
  "明天": "Minh thiên",
  "昨天": "Tạc thiên",
  "星期": "Tinh kỳ",
  "月": "Nguyệt",
  "号": "Hiệu",
  "年": "Niên",
  "上午": "Thượng ngọ",
  "下午": "Hạ ngọ",
  "晚上": "Vãn thượng",
  "想": "Tưởng",
  "能": "Năng",
  "会": "Hội",
  "可以": "Khả dĩ",
  "觉得": "Giác đắc",
  "因为": "Nhân vi",
  "所以": "Sở dĩ",
  "虽然": "Tuy nhiên",
  "但是": "Đản thị",
  "而且": "Nhi thả",
  "更": "Cánh",
  "最": "Tối",
  "很": "Hấn",
  "太": "Thái",
  "真": "Chân",
  "常": "Thường"
};

export const getHanViet = (text: string): string => {
  if (!text) return "";
  const result = text.split("").map(char => {
    return HAN_VIET_DATA[char] || char; // Simplified: just return char if not found
  }).join(" ");
  return result;
};
